### ISSUE TITLE
please change naming convention of your document

### ISSUE THREAD

**Issue by javadbat** [Sinakhx/array-slayer#3]
as i read your doc i notice you use below term
```
import _ from "arraySlayer";
```
please change _ to ArraySlayer or something else.
using special char  like $ , _ ,.... is not a good practice nowdays it make code unreadable and its not compatible with js natural naming system

**Comment by Sinakhx** [comment]
Hi, thanks for your consideration & feedback. Surely i'll change it to a more meaningful name ASAP.
